### PR TITLE
Remove brain trauma strings, godwoken syndrome, merge dumbness with speech impairment

### PR DESCRIPTION
**Pull request by atakiya**
## About The Pull Request
HURR DURR
No but really, forcing people to say random shit is not good in an RP environment.
We could technically do this better in some way, but the best would be to actually convert any speech they do into something else, like drunkenness or similar.

For now though, lets just get rid of this.

Edit:
Also removed godwoken syndrome, to get rid of the braindamage strings file

Edit 2:
Merged `TRAIT_UNINTELLIGBLE_SPEECH` with `TRAIT_DUMB`
But also removed unintelligible for now as its too aggressive on wordings. This should be adjusted in another PR.
Did a little refactor on derpspeech variable, as it was already handled like a boolean.

## Why It's Good For The Game
Less NYAAAAA~~

## Changelog
:cl:
del: Removed braindamage forcing you to say random lines
del: Removed godwoken syndrome
del: Removed unintelligble speech trait, mutation now uses dumbness instead
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
Mind removing every feature referencing `BRAIN_DAMAGE_FILE` aswell as the string file itself?

**Comment by atakiya** [comment]
> Mind removing every feature referencing `BRAIN_DAMAGE_FILE`, the define aswell as the string file itself?

That would include everything with the voice of god. But I could.

**Comment by Azarak** [comment]
Yeah that would be good. If you want an easy implementation you could prob() to send messages such as "You are having trouble forming coherent thoughts" aswell.

**Comment by atakiya** [comment]
And I'm good once more.

**Review by Azarak — APPROVED** [review]

**Pull request merged**
