### PR TITLE
Misc map cleanup (ruins, shuttles, etc)

### PR DESCRIPTION
**Pull request by atakiya**
## About The Pull Request
Removes unthematic or low effort ruins, shuttles and such that can't be fixed or won't be fixed right now.

For those interested in fixing those, checkout the old copy from before this commit. It's all in the git history.

## Why It's Good For The Game
Less pollution.

## Changelog
:cl:
del: Removed unthematic ruins and other misc sub-maps
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
Wasn't listening station the DJ station? I think that one was rather comfy

**Comment by atakiya** [comment]
> Wasn't listening station the DJ station? I think that one was rather comfy

You can check here: https://github.com/hrzntal/horizon/pull/846/checks?check_run_id=5169735638

Also: 
image

**Comment by Azarak** [comment]
I like the listening outpost too

**Comment by atakiya** [comment]
> I like the listening outpost too

Cool. I don't.

**Comment by Azarak** [comment]
Why do you consider it broken or non-thematic? Is it because it's syndicate themed? That could be changed. We don't really have many ruins and I would hate to see passable and interesting ones be pruned

**Comment by atakiya** [comment]
*   It is a slot for someone to just sit in space and do nothing (for our purposes) aside of radioing
  *   Yes the syndicate thematic too
There’s no reason for ruins that split people even more apart when we are already at nullpop.
If you want to fix the ruin, then do so. The files are still in the git history.

**Comment by atakiya** [comment]
Maybe some other day the rest will be looked at.

**Pull request merged**
