### PR TITLE
nomming mechanics

### PR DESCRIPTION
**Pull request by Seris02**
\**noms u*\*
## About The Pull Request

So basically, has this UI:

Screenshot 2021-11-14 014050

Screenshot 2021-11-14 014105

And you press this while pulling someone to nom them:
the nom button

Almost entirely modular, and built for ease of addition (hopefully)

Current vore modes:
- Hold
- Digest
- Absorb
- Unabsorb

Screenshots are a teensy bit outdated, they don't show the essence cube revitalisation mechanic toggle. So basically, you can turn on a mechanics toggle so that you simply get turned into a small cube instead of being qdeleted and poofed from existence when digested.

# Does not include vore noises, simplemob or cyborg vore

## Why it's good for the game

vore is nommy and nice

## Changelog

:cl:
add: vore mechanics
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
The biggest thing I'd want changed is to have all the variables on a level of a new datum
/datum/vore_belly
which would communicate with the /obj/vbelly
and vbelly would only do callbacks to vore_belly
and as little behaviour as it's possible
`vbelly` pretty much acting only as a token physical object for the proper `vore_belly` datum

**Review by atakiya — COMMENTED** [review]
@Azarak if you're happy with the changes, please approve.
We can then **testmerge** it on the next deploy after. :)

**Comment by Azarak** [comment]
There's not enough documentation, new procs and variables should be commented (one line comments for procs are fine imo)
I think I'm too sick to give it a proper review right now. There are some changes I'd like to see but they can be done later

**Review by Azarak — APPROVED** [review]

**Comment by atakiya** [comment]
> There's not enough documentation, new procs and variables should be commented (one line comments for procs are fine imo) I think I'm too sick to give it a proper review right now. There are some changes I'd like to see but they can be done later

I'll make an issue for it. Not the best solution, but I guess that can be dealt with.
(get well soon!)

**Comment by atakiya** [comment]
@Seris02 Would there be any changes/fixes possible to be done, or do you consider yourself "done" with this?
Asking as I recall you mentioning to not wanting to touch this further.
This is **not** about adding any features, I'm aware that this could be done later.

To put it short, there's a few bugs blocking this from a full-on merge.

**Comment by atakiya** [comment]
@Seris02 The currently biggest issue I can find is that mobs/players inside a belly can still use *any* items. This includes guns and other somewhat nonsensical things.
You can probably see where the issue with that is 😄 

If filtering out items is too much of a drag, this could easily be fixed by just disallowing usage for now, although it would still be appreciated if PDAs or similar were accessible, but again, I'll leave that up to you.

Else I'll have another look over the code at some point next week hopefully and let you know if there's anything else amiss.

**Comment by CypressBz** [comment]
had someone complain the vore button is still visible when vore's disabled in prefs.

**Comment by Seris02** [comment]
> had someone complain the vore button is still visible when vore's disabled in prefs.

honestly I have no clue how, I did literally everything I could think of to make sure that was impossible
did they mean the UI button or the verb?

it might be because I if they reset the changes made, that it didn't set them there because it doesn't update the button during the loading of vore pref slots
but that's like the only thing I can think of that might be it

**Pull request closed without merging**
