### PR TITLE
Fixes name for Thermomachine circuit in designs

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Fixes https://github.com/hrzntal/horizon/issues/736

## Changelog
:cl:
fix: Fixes name for Thermomachine circuit in designs
/:cl:

### CODE REVIEW

**Comment by atakiya** [comment]
I think we should just rename these to what they *really* are - heatpumps.
Thermomachine makes no sense, freezer/heater is outdated as well.

**Comment by Azarak** [comment]
> I think we should just rename these to what they _really_ are - heatpumps. Thermomachine makes no sense, freezer/heater is outdated as well.
> 
> Your thoughts on it?

That sounds good I can rename them all in a bit

**Comment by atakiya** [comment]
> > I think we should just rename these to what they _really_ are - heatpumps. Thermomachine makes no sense, freezer/heater is outdated as well.
> > Your thoughts on it?
> 
> That sounds good I can rename them all in a bit

Alright, undraft it once done, please.

**Comment by Azarak** [comment]
I'll make a new PR

**Pull request closed without merging**
