### PR TITLE
Airlock and shutters sprites update

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Updates airlocks, shuttlers and blast doors to match the 3/4th perspective.
The airlocks and shutters automatically align their direction so they dont have to be aligned in mapping, or construction.
dreamseeker_2022-01-08_13-06-45
dreamseeker_2022-01-07_20-55-48
dreamseeker_2022-01-07_20-54-09
dreamseeker_2022-01-06_19-52-33
dreamseeker_2022-01-07_14-33-18

Most assets taken from baystation12. I have adjusted a lot of them and made a lot of missing overlays.
Radiation, glass shutters made by me
Public airlock sprites made by me

## Changelog
:cl:
add: Airlock and shutters sprites update
/:cl:

### CODE REVIEW

**Review by MissFox0810 — COMMENTED** [review]
Whats with the changes to the maps?

**Comment by Azarak** [comment]
The airlocks on maps have been var edited to use some prebaked icons, those no longer exist in favor of overlays

**Review by atakiya — APPROVED** [review]
Good to go from my side. Wait on @MissFox0810 for approve & merge.

**Review by MissFox0810 — APPROVED** [review]
Ok, happy with this. Approving and merging

**Pull request merged**
