### PR TITLE
Add maintainers to codeowners for critical paths

### PR DESCRIPTION
**Pull request by atakiya**

### CODE REVIEW

**Comment by atakiya** [comment]
@Azarak @MissFox0810 Feel free to comment suggestions for either of you as well until this is merged.
If done, just approve.

**Comment by MissFox0810** [comment]
Might be easyer to make me code owner for SQL and mapping

**Comment by Azarak** [comment]
I can't think of anything for me specifically, I touch a lot of places.

**Comment by atakiya** [comment]
> I can't think of anything for me specifically, I touch a lot of places.

It's mainly for stuff you want to be notified of that changes.
So say, I touch the story teller and you are the codeowner of the file with it, you'll get an email/push notification or similar when I post a PR with it.

It's not required to do reviews on them, but this is to ease seeing important changes crop up.

**Review by MissFox0810 — APPROVED** [review]

**Pull request merged**
