### PR TITLE
Adds more ruins

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
So there's an entire gamemode centered around exploring, when there's nigh nothing in terms of ruins to explore.
Yeah, even my "I have been awake for too long" brain isn't having that. So here's three ruins mostly hot off the presses, with loot and environmental storytelling. Includes two space ruins and one planetary ruin.

### This PR also fixes a bunch of atmos diffs in space ruins. It does not address the atmos diffs in planetary ruins, as the system isn't in place for it yet.

ocee5
ocee6
ocee7

## Why It's Good For The Game
look if this is gonna be topdown starbound it better at least have some cool ruin generation

## Changelog
:cl:
add: Added three new ruins to the roster.
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
I'm not sure how I feel about that Sseth's reference ruin, the other two look pretty good!

**Comment by unit0016** [comment]
> I'm not sure how I feel about that Sseth's reference ruin, the other two look pretty good!

Less obvious than aesthetic is

**Comment by Azarak** [comment]
And it's why I wouldn't have no qualms about removing the aesthetic one. Hm. Thoughts about reference ruins @MissFox0810 ?

**Comment by unit0016** [comment]
> And it's why I wouldn't have no qualms about removing the aesthetic one. Hm. Thoughts about reference ruins @MissFox0810 ?

Fair nuff. ~~Put the least time into it anyways, and that's apparent.~~

**Review by MissFox0810 — COMMENTED** [review]
Have these maps been AT checked? We have had a spot of ruins being added that have been causing a lot of AT issues.

**Comment by MissFox0810** [comment]
Converted to draft until AT check has been done. due to what looks to be airless and air tiles mixed together.

**Comment by unit0016** [comment]
AT Check mostly successful, though revealed a bunch of other ruins with them. I'm going to fix what I can before I reopen proper.

**Review by Azarak — APPROVED** [review]

**Pull request merged**
