### PR TITLE
Adds shotglass states to secondary drinks.dmi

### PR DESCRIPTION
**Pull request by CASEYGUNGEON**
## About The Pull Request

Adds `shotglassclear` and `shotglassoverlay` states to `icons/horizon/obj/drinks.dmi`

## Why It's Good For The Game

Lets drinks in that dmi have generic shotglass graphics instead of disappearing when poured.

## Changelog
:cl:
fix: Fixed poured shotglasses disappearing
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
Could you instead make it so the states from the `icons/horizon/obj/drinks.dmi` are moved into `icons/obj/drinks.dmi` and the code doesn't use that icon file anymore? The specific `/horizon` folders are artifacts from when we still downstreamed off of TG long time ago.

**Comment by CASEYGUNGEON** [comment]
thought i'd ask why they were in a different file but figured there was a more substantial reason. should be able to do that

**Comment by Azarak** [comment]
Thank you!

**Comment by atakiya** [comment]
This is going to conflict and made useless with #1178

**Pull request closed without merging**
