### PR TITLE
Adds Sensors to tacticool turtleneck/skirtleneck

### PR DESCRIPTION
**Pull request by CypressBz**
## About The Pull Request
Adds sensors to the Tacticool Turtle and skirtle neck

## Why It's Good For The Game
Sensors on loadout items good.

## Changelog
:cl:
qol: Add Sensors to the Tacticool Turtleneck and Skirtleneck
/:cl:

### CODE REVIEW

**Review by atakiya — APPROVED** [review]

**Comment by Azarak** [comment]
Those aren't the tactiCOOL versions, these are the armored syndicate tactical ones.

**Comment by atakiya** [comment]
> Those aren't the tactiCOOL versions, these are the armored syndicate tactical ones, which should not have sensors.

Oh those are armored.. whoops.

**Review by atakiya — CHANGES_REQUESTED** [review]
Yeah that should be reapplied to `/obj/item/clothing/under/syndicate/tacticool`

Kind of dumb that it inherits from that type but whatever, out of scope of this PR to fix that.

**Comment by CypressBz** [comment]
I'll have to look again, pretty sure the tacticool version inherits everything from the tactical version and strips the armor.

**Comment by atakiya** [comment]
> I'll have to look again, pretty sure the tacticool version inherits everything from the tactical version and strips the armor.

Correct, but thats where you have to move the sensor variable change to, as well. it's right below.

**Comment by CypressBz** [comment]
> > I'll have to look again, pretty sure the tacticool version inherits everything from the tactical version and strips the armor.
> 
> Correct, but thats where you have to move the sensor variable change to, as well. it's right below. I'd have put a suggestion but GitHub doesnt want me to.

I'll have to go hunting for that variable again, it defaults to having sensors, then overrides those when it doesn't want them.

**Comment by atakiya** [comment]
> > > I'll have to look again, pretty sure the tacticool version inherits everything from the tactical version and strips the armor.
> > 
> > 
> > Correct, but thats where you have to move the sensor variable change to, as well. it's right below. I'd have put a suggestion but GitHub doesnt want me to.
> 
> I'll have to go hunting for that variable again, it defaults to having sensors, then overrides those when it doesn't want them.

All you have to do is to add
`has_sensor = HAS_SENSORS`
to (wait for edit)

**Review by atakiya — APPROVED** [review]

**Pull request merged**
