### PR TITLE
Ruins Removed

### PR DESCRIPTION
**Pull request by CypressBz**
## About The Pull Request
This removes three space ruins and a lavaland ruin
the three space ruins in question are:
_maps/RandomRuins/SpaceRuins/clownplanet.dmm
_maps/RandomRuins/SpaceRuins/originalcontent.dmm
_maps/RandomRuins/SpaceRuins/shuttlerelic.dmm

The lavaland ruin is:
_maps/RandomRuins/LavaRuins/lavaland_biodome_clown_planet.dmm

For being antithematic, and low value outside of pretending you didn't see them iccly.

## Why It's Good For The Game
Opens more space for ruins added by our wonderful mappers.
Removes overtly memey content.
improves deep space atmosphere
all of this is purely opinion based work.

## Changelog
:cl:
del: removes clownplanet.dmnm and all references to it in the code
del: removes originalcontent.dmm and all references to it in the code
del: removes shuttlerelic.dmm and all references to it in the code
del: removes lavaland_biodome_clown_planet.dmm and all references to it in the code
/:cl:

### CODE REVIEW

**Comment by CypressBz** [comment]
woops I fucked up
one second.

**Comment by CypressBz** [comment]
ffs the update's supposed to be for a different pr.

**Comment by atakiya** [comment]
Undrafting on request of @CypressBz

**Review by atakiya — APPROVED** [review]
Looks fine to me.
Waiting on approval from @Azarak to merge.

**Review by Azarak — APPROVED** [review]

**Pull request merged**
