### PR TITLE
Ports the /tg/ drink-desouling update & new recipes

### PR DESCRIPTION
**Pull request by Delnth**
## About The Pull Request
Brought to the /tg/ drink desouling sprite update to the server, along with a bunch of recipes that we did not have.

## Why It's Good For The Game
Drinks look a lot better, it's niche but immersion can make the difference.

### Thirdparty Credits
tgstation & Crumpaloo - original desoul PR (tgstation/tgstation#66538) and additions
atakiya - fixups of >10 sprite errors, glass and shotglass overlays

## Changelog
:cl: Delnth, /tg/station & Crumpaloo, Alex 'Avunia' Takiya
add: Milkshake recipes have been changed
add: Ported caramel milkshake
add: Ported Space Ale
add: Ported a few drinks from /tg/
add: Added a new reagent to the soda dispenser, the aquafaba. An alternative to egg white.
imageadd: Ported drink sprites from /tg/
imageadd: Ported crushed can sprites from /tg/
imageadd: Ported poster updates from /tg/
imageadd: Ported tiny edit on space-up vendor from /tg/
imageadd: (atakiya): Added overlays for the new glass and shotglass sprite
/:cl:

### CODE REVIEW

**Comment by Delnth** [comment]
Do not merge yet, I need to polish it and readd the synthanol bottle sprite

**Comment by atakiya** [comment]
> Do not merge yet, I need to polish it and readd the synthanol bottle sprite

please make drafts in that case, or convert your request into a draft
image

I've gone ahead and done so already, but please keep this in mind for the future!

**Comment by atakiya** [comment]
- Conflicts have been fixed.
- I also removed some drink recipes or drinks that we shouldn't currently have.
I'd rather check/adjust those in a later PR - the sprites have been left in however, so we can use them then.
- Updated the changelog with the new changes
- Changed milkshakes to also use ice, which also had me use different reagents now. It's a mess but it'll do for now, we'll make drink mixing much better in the near future
- Removed the nanotrasen shaker, and any dead code

For some of the residual changes, just check the commits. I hope this all is fine.

**Comment by Delnth** [comment]
Looks good to me. Could've simply removed the effects from the new drinks instead of removing them entirely but that's fine really. Figured adding them would help not cause confusion if people were to try and make these drinks using the /tg/ wiki. I suppose they can be added again later.

**Comment by atakiya** [comment]
> Looks good to me. Could've simply removed the effects from the new drinks instead of removing them entirely but that's fine really. Figured adding them would help not cause confusion if people were to try and make these drinks using the /tg/ wiki. I suppose they can be added again later.

Yeah I can understand that, though the ones I removed were also a bit.. "eh", with lore mostly from TG things which we don't really want to keep either.
I did keep the other ones that were more generic.

Also it should be recommended to use the reaction search ingame for drink mixing anyways, as we will be straying away from the wiki more and more.

**Review by MissFox0810 — APPROVED** [review]

**Pull request merged**
