### PR TITLE
Cultural and Languages update

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request

Adds in culture stuff much like in Baystation
Currently only featuring human, generic and lizardperson culture stuffs
Everyone gets 5 linguistic points, which they can spend on languages, 1 to understand, 2 to speak it (so you can get 2 spoken 1 understood at most as of now)
New languages added related to the cultures: Spacer, Russian, Selenian, Gutter
People can buy languages only if their species, or background somehow relates to it
Common is NOT inclusive, and you can choose to not know common, however, you'll be limited to a very small amount of jobs. Hooray language barrier RP
3 of your "initial paychecks" are now scalled with the economic powers of your background, so come from Luna, get dosh, come from Lavaland, be poor.

### CODE REVIEW

**Comment by hrzn-actions** [comment]
#### Test Merge Deployed

##### Server Instance
Horizon

##### Revision
Origin: e75a91cd31fd2f09af92f31effc1be6eb929a4c6
Pull Request: 7592212938981a29f996912e9f67198c587e61e5
Server: 9a1f4b88b6a4a21a8a987a3821201f025f0d95de

**Comment by hrzn-actions** [comment]
#### Test Merge Updated

##### Server Instance
Horizon

##### Revision
Origin: 356d44205bcc5cdab4e63a47e189a4ce8475dfea
Pull Request: 7592212938981a29f996912e9f67198c587e61e5
Server: 40df0f4dda3c7008cf16fd1b65221dc1a9870892

**Review by Avunia — APPROVED** [review]
Testmerges seem to work well. Great job!

**Comment by hrzn-actions** [comment]
#### Test Merge Removed

**Pull request merged**
