### PR TITLE
Pipe overlays overhaul and bitmasking

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Normal and smart pipes now use bitmasked sprites, instead of 4 buggy overlays. Removed the unessecary caches and other dumb stuff all across the pipe overlays, adjusted colors and some sprites. 

I have yet to conduct bitmasking on HE pipes, but the binary ones dont use overlays so it isn't a high priority anyway

The pipes and other atmospheric machinery will now properly show up on multiz now, the decreased amount of overlays should help performance too

During making of this PR I found like 5 seperate bugs regarding smart pipes and holy shit I need to fix them
dreamseeker_2021-07-06_05-57-54
dreamseeker_2021-07-06_05-57-39

## Changelog
:cl:
fix: Some seemingly incorrect pipe overlays will now be correct
refactor: Pipe overlays overhaul and bitmasking
/:cl:

### CODE REVIEW

**Comment by Ghilker** [comment]
oh my that's a great work! only thing i found is that when you place a single pipe without any connections it won't have an icon, i'll port this to tg when you done :3

**Comment by Azarak** [comment]
> 
> 
> oh my that's a great work! only thing i found is that when you place a single pipe without any connections it won't have an icon, i'll port this to tg when you done :3

Mhm, that's only cause I check for a case with 1 connection, where I should check for 0 or 1. Smart pipes are quite quirky in how they "connect" to all directions but you're not supposed to render exposed pipes everywhere. Which kinda sucks, I liked exposed pipes in the normal pipes. I'll fix that though

**Comment by Azarak** [comment]
And fixed that issue

**Review by atakiya — APPROVED** [review]
Will TM after some previous TMs are merged.
Code looks nice!

**Review by atakiya — APPROVED** [review]
Was TM'd for about a week now, no apparent issues.

**Pull request merged**
