### PR TITLE
Cypress's Icebox Changes

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
A PR with QoL changes and bugfixes PRed on behalf of Cypress.
• Fixes powernet issue in interrogation room
• Missing pipe in port quarter maints
• Re-piped large portion of lower maints.
• Heatpump radiator loops for science, medical, scrubbers and the SM.
• Redesign of engine room.
• Removed turbine fuel to AI satellite pipe from roundstart.
• Repiped the SM.
• Removed "SPACE" warning posters leftover from space Boxstation.

## Why It's Good For The Game
Quality of life updates and manually mapped supermatter piping that also has less chance of causing delams.
Fixes a few bugs.

## Changelog
:cl: Cypress
add: New redesigned engine room.
qol: Heatpump radiators for science, medical and scrubbers.
fix: Powernet and piping issues on Icebox.
/:cl:

### CODE REVIEW

**Comment by KathrinBailey** [comment]
@CypressBz  <= all credit to cypress for the PR.

**Comment by CypressBz** [comment]
@atakiya 
@MissFox0810 
Looks like this just needs looked over from someone.

**Review by MissFox0810 — CHANGES_REQUESTED** [review]
Seems there is a Pipe in the SM not connected.
image

**Comment by atakiya** [comment]
T pipe under heat pump should be a 4-way. Is currently not connected to the cryo tubes.
image

**Comment by CypressBz** [comment]
If this is all for the bug fixes, this is just waiting on Kaths finished mining overhaul. so can probably be merged. I've scoured the stuff I touched myself, the pipe Foxie is talking about can be rerouted after that, or I can draw a line for kath to follow, but Atmos is going to be overhauled next.

**Comment by CypressBz** [comment]
Yeah, I'll do a full bug hunt for technical issues after. This was a bit of a weird situation cause Kath and I had bother started working on Icebox remapping without talking to eachother. and originally Kath was just going to merge my work into hers. after this we're back to taking turns though, so it should be a little more simple after we've got this, and she's finished with her stuff.

**Comment by atakiya** [comment]
I'm kind of not fazed to merge a map with a lot of broken atmos devices (vents and scrubbers around engineering mostly)

But I guess if it has to be done..

**Review by atakiya — APPROVED** [review]

**Comment by atakiya** [comment]
If a week after merge, there's no fix for most of these, this will be the first and last time. Just a fair warning.
I understand the situation, but I don't want this to become a common thing to merge broken stuff.
Main should always be in a working state, as much as possible.

**Comment by MissFox0810** [comment]
Talked to Cypress about this, going to merge this, then he will work on the fixes asap

**Pull request merged**
