### PR TITLE
Makes Underwears Actually Work

### PR DESCRIPTION
**Pull request by EmilitiaEnnehrt**
## About The Pull Request
Makes it so that underwears hides it's respective genitals, Those with undershirts, bras, panties, etcetera will no longer have their parts sticking out when not wearing clothes or wearing only pants. Obviously, genitals can still be toggled exposed through IC verb, but no more would medical have to see bits sticking out or those with particular outfits sporting midriff, etc, have to toggle hide their breasts everytime.

## Why It's Good For The Game
Quality of life, makes things more sensible, medical & security no longer have to always look at bitty bits when doing their jobs (surgery/processing), but of course if you want to show off you can still do it no problem.

## Changelog
:cl:
fix: underwear now hides genitals
code: added a cover check variable to underwears
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
Your code doesn't actually do anything, and this behaviour is already implemented inside respective's genitals `is_hidden()` proc such as here https://github.com/hrzntal/horizon/blob/main/code/modules/mob/dead/new_player/sprite_accessories/genitals.dm#L44

**Comment by EmilitiaEnnehrt** [comment]
> Your code doesn't actually do anything, and this behaviour is already implemented inside respective's genitals `is_hidden()` proc such as here https://github.com/hrzntal/horizon/blob/main/code/modules/mob/dead/new_player/sprite_accessories/genitals.dm#L44

huh, doesn't the parts go on top of underwear sprites by default?

**Comment by Azarak** [comment]
Well, you have added a variable but it is not used anywhere in code. Currently it's implemented in a hacky way because the underwear is not clothes but just an accessory, but it's fine for the time being. And you don't need to toggle your parts on/off, you only have to toggle the underwear on/off and it will show/hide your parts appropriately.

**Comment by EmilitiaEnnehrt** [comment]
> Well, you have added a variable but it is not used anywhere in code. Currently it's implemented in a hacky way because the underwear is not clothes but just an accessory, but it's fine for the time being. And you don't need to toggle your parts on/off, you only have to toggle the underwear on/off and it will show/hide your parts appropriately.

The var is used on clothes themselves, and I think testing it has worked, but I will try testing it on and off again. I think the only explanation for this might be that underwear hiding part is broken for me personally on the live server and I thought the reason was this.

**Pull request closed without merging**
