### PR TITLE
Fixes two overflow pixels on the male digitigrade chest

### PR DESCRIPTION
**Pull request by atakiya**
## About The Pull Request
Fixes two overflowing pixels that would show up outside of almost every clothing article that covered the legs.

image *Removed pixels marked in red*

## Why It's Good For The Game
No more thigh showing. 🗞️

## Changelog
:cl:
imageadd: Fixed two rogue pixels on the male digitigrade chest, which caused pants to not fully cover your legs. Stay warm and fluffy now.
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
Also an issue on mammal female chests, and slime female chests.

**Comment by atakiya** [comment]
how's it an issue on the female body? from what I can tell the entire body is one pixel less tall, which means those pixels aren't at all visible.
unless you mean different pixel locations.

I'll check the slime chest though

________________________________

**Comment by Azarak** [comment]
Oh I thought it was at the same height, if it's 1 pixel above then it should be fine my bad

**Review by Azarak — APPROVED** [review]

**Comment by atakiya** [comment]
Slime bodies are correct too.
This wouldn't even be an issue if the plantigrade feet only existed, as the pixels are covered by them anyways.

Checked all the other bodies too, this is the only one with 7 pixels margin on the bottom, odd.

**Pull request merged**
