### PR TITLE
Cypress' Mega Ruin Map Redux!

### PR DESCRIPTION
**Pull request by CypressBz**
## About The Pull Request

**SPOILER WARNING: YOU WILL SEE A LOT OF CONTENT OOCLY IF YOU GO DOWN THIS LIST.**

This is a full overhaul of the older TG station ruins, as well as minor retouches of some unique horizon ruins, I have been working on this for days on end now and I really hope you like it, I tried to keep the balance clear, by increasing length or difficulty of dungeons I added additional loot to.
All adjustments from this PR, excluding a couple, as well as maintaining suggested changes from comments have been added to space ruins. #296

<details>
  <summary>Images of each map side by side!</summary>
  
  Abandoned Zoo:
image
Asteroid1:
image
Asteroid4:
image
Big Derelict1:
image
Derelict2:
image
Derelict3:
image
Derelict4:
image
Derelict5:
image
DJ station
image

Gas The Lizards
image

Hilberts hotel testing site
image

mrow thats right
image

old AI sat
image
image
image

one half
image

turreted outpost
image

vaporwave
image

way home
image

Abandoned factory
image

crashed pod
image

deserted lab
image

lodge
image

</details>
<details>
  <summary>detailed (overly) changelog!</summary>
  
Random space ruins

	Abandonedzoo.dmm: 
		Removes interior walls between the cages and main room, because what's a zoo with out some spectating windows?
		Replaces riotshield with a couple random loop spawners, the ruin already contains a floragun, and a temperature gun.
		replaces generic space suit with a medical hardsuit as changed in above PR
		moves a few tables around, keeping the loot, while facilitating the wall changes.
		moves some various furniture around.
		cheanged and filthied the place up, to make it look lived in
		added space cleaner bottle next to operating table.
		
	asteroid1.dmm
		condensed the asteroids down to a single rock, while maintaining approximate minability.
		shrank map to reduce footprint, to facilitate reducing cost at a later date.

	asteroid4.dmm
		Removed a clown, replaced with remains, blood, and a knife.
		adjusted shuttle to facilitate showing off the new decor
		
	bigderelict1.dmm
		Blocked off the back entrance to make the map more linear, forcing you to go through the monsters to get the good stuff.
		replaced a 1911 spawn in the middle of the monnsters, with an energy weapon random loot spawner, before the monsters, to assist people who didn't come prepared.
		added rusting walls to increase the atmosphere a little.
		moved corpse, another 1911 spawn, gps, and bloody note to a different section of the ruin to facilitate running gelatinous floors and walls to the back entrance. (which was right next to the body)
		moved hatchling to center of ruin to force at least one instance of combat for loot.
		
	Derelict2.dmm
		kept the set placement, and general theme
		removed three directional airlocks from the ruin, keeping one and making it look like it broke off a station.
		added atmos set to off
		added rust, and filthied the place up
		shrank map to reduce footprint, to facilitate reducing cost at a later date.

	derelict3.dmm
		replaced a vast massive empty ruin, with a smaller, more substantially story telling one.
		outright entire replacement of old ruin.
		
	derelict4.dmm
		reduced footprint while maintaining content
		shifted asteroids into empty spaces
		shrank map to reduce footprint, to facilitate reducing cost at a later date.
		
	derelict5.dmm
		reduced footprint while maintaining content
		shifted asteroids into empty spaces
		shrank map to reduce footprint, to facilitate reducing cost at a later date.
		
	DJstation.dmm
		reduced solars count.
		wired solars to smes
		added solar tracker and computer
		added functional atmos
		added donk pocket box spawn
		added more flavor to the dj's room by way of a wardrobe.
		Made the satelite look more satilitey
		added flith
		replaced overly bright white tiles with textured grey tiles
		shrank map to reduce footprint with the removal of excessive solar panels, to facilitate reducing cost at a later date.
		replaced eva suit and helmet with orange spacesuit and matching helmet as changed in above PR

	gasthelizards.dmm
		add filth
		broke one cell window
		replaced some walls with rusty walls.
		Replaced EVA suit storage with Security suit storage as changed in above PR

	hilbertshoteltestingsite.dmm
		added filth
		reduced empty space to both make the turrets harder to handle for the good loot, and to reduce map foot print.
		maintained all original content.
		
	mrow_thats_right.dmm
		added flith
		replaced n2o gas miner with an n2o tank connected to a passive valve.
		
	oldAIsat.dmm
		Massive overhaul to structure to trim away tiles and turfs you won't notice as a player
		reduced overall footprint.
		added multiple locked firelocks to increase difficulty of ruin diving.
		added set decoration, as well as addition trash spawning
		added filth
		replaced a lot of walls and turfs with rusted variants.
		added vending machines to front room.
		replaced some lights with red variants to increase atmosphere
		added additional machine frames, and computer frames to make it feel less empty.
		added more living commodities to make it look lived in.
		added a couple secure crates to add additional content
		added tcomms structures, and machine frames to room on east most edgeto add additional filler
		replaced strange emtpy torture chamber on top right with a breached living space, complete with a locked bathroom.
		replaced soda and snack vendor in living space with random variants
		added microwave and donk box spawn to living space
		moved table in living space to the breached corner and added a small storytelling element
		added watercooler to living space
		added two x4 explosives spawns to locked bathroom to facilitate concrete interactions with future and current content on planets.
		added barricades to some doors to increse length of ruin diving
		replaced all full directional window spawners with fulltile window spawners
		added fire closets in three places
		improved AI core with additional set dressing
		added a dummy AI station with intercoms and a machine frame where the AI would go.
		added an additional story telling element to the ai core
		added some shocked grills and obstacles to ai core
		added a randomloot hardsuit spawner behind obstacles
		added random loot crate spawn
		added copious red circuit tiles to floors as well as a small stack (6) in the corner of the air core.
		added some of the new signage around the whole place
		
	onehalf.dmm
		added filth
		replaced snack vendor with random snack vendor
		added iron ore in a mining dron launch bay
		increased ammount of diamonds to launch bay with 1 diamonds to 4 diamonds
		added cash to safe
		replaced EVA suit and helmet with blood red hardsuit in safe 
		removed stethiscope to make the ruin harder to clean out.
		
	turretedoutpost.dmm
		Replaced many walls with rusty varriants
		added filth
		
	vaporwave.dmm
		added radiant dance machine
		added space carp hardsuit
		added a proper double door airlock
		adjusted turfs to facilitate airlock
		
	way_home.dmm
		reduced footprint while maintaining content
		shifted asteroids into empty spaces
		shrank map to reduce footprint, to facilitate reducing cost at a later date.
		added small story telling elements to increase content on an otherwise barren ruin.
		added space suit, eva helmet, empty oxygen tank, and breath mask
		added two chairs, a holofirelock, an unlit bonfire, and a ration pack
		added a small pocket of breathable atmos behind holofirelock
		

planetary ruins:

	abandoned_factory.dmm
		replaced all walls with concrete walls
		replaced some interior planetary tiles with plating
		replaced office window shutters with blast doors
		replaced loose girders with rubble
		replaced all instances of planetary stone with concrete turf, or concrete/reinforced turf
		removed duplicate container, crate and closet spawners in the same place, opting for the crate.
		added additional clear terrain spawners around edge of map
		replaced girders with rubble
		added rubble
		
	crashed_pod.dmm
		increased map size slightly to facilitate storytelling
		made shuttle look crashed
		added turf around to make the ground look like a crash zone
		replaced solar area with a jank emergency solar setup
		replaced burst engines with proper gas fueled ones.
		made engines symetrical
		spaced engines out behind the ship for story telling
		smashed front of ship to make it clear it's not flyable.
		added wooden barricades to one window
		added very basic atmos systems to make it clear the engines aren't burst engines.
		maintained orginal loot.
		
	deserted_lab.dmm
		Replaced standard walls for concrete walls
		added a small power system
		bolted the cells
		added plasma to crates out back to facilitate powering the ruin to unbolt the doors.
		
	lodge.dmm
		Replaced metal girder wood walls with all wood walls, to make it more natural feeling if improved
		replaced reinforced windows spawners with window spawners
		added additional table lamp to the kitchen
		added container bowl to kitchen
		added fireplace to dining room
		added pile of logs to dining room
		added additional 2 chairs to dining room
		added filth
		added a trash can
		changed the carpet to make it look more like a rug thrown on the floor opposed to cerpeted floors.
		added book shelf
		added random guidebook spawn
		added dirt to garden and bath frrom door to garden
		added a small shed
		added parts to set up power in the lodge to shed
		moved utility items, like the water tank and scrubber to shed
		removed one of two scrubbers
		added a hatchet and additional building materials to house
		added a cabinet with shoes near door.
		moved shotgun from front door to the fireplace mantle, and ammo to cabinet in bedroom
		added alchohol bottle spawner to bed room
		added a sofa to bed room
</details>

## Why It's Good For The Game

adding new high quality content from mappers makes the old ones look even worse.
I maintained the feel of any ruin I touched, while adding clutter, filth, debris, loot, and random junk!
some maps were shrank to reduce their foot print, while very few were expanded to increase story telling chances.
All changes are documented, if rather roughly in some vague things, like filth, and story elements.

## Changelog
:cl:
add: Many new decorations to many ruins.
add: many more loot spawns to many ruins
add: filth and rust to many maps, to make them look lived in, and ruinous.
add: more randomization on certain things like vending machines and other interactables
add: obstacles and things to extend dungeon diving slightly in some of the high loot ruins
del: outdated looking decor in places
del: reduces some maps size, by condensing them, or removing edge fluff
balance: adds more space cash where it seems logical, as well as plenty of new loot spawners
/:cl:

### CODE REVIEW

**Comment by atakiya** [comment]
## For maintainers
Please check some of the ruins, and display in your approval/change request which ones you checked and any issues.

## OP
@CypressBz This might take a few days to get checked through, but its very appreciated.

**Review by MissFox0810 — APPROVED** [review]
Looked over all the maps. Only minor issues i have but will still approve. Is some of the derelict maps are perhaps a bit to heavly shrunk. but could prehaps be fleshed out with more additional derelicts or debry during runin level loads.

Other than than, wow nice work. you fixed quite a few issues i had with some of the maps.

**Comment by CypressBz** [comment]
I've been given the go ahead to actually weight the ruins, so I'm hoping that will alleviate the issue. I plan on making the no loot, small ruins very cheap, to allow bigger ones to spawn. and weighting the cost of each on size and loot.

**Comment by CypressBz** [comment]
fixed some stuff while I was documenting the changes, forgot to press save before the PR. duuuuh

**Review by Azarak — APPROVED** [review]
I've seen screenshots of most of the changes. Really good stuff

**Review by atakiya — APPROVED** [review]
Yeah this is pretty good.

**Pull request merged**
