### PR TITLE
Energy Gun Visual Update!

### PR DESCRIPTION
**Pull request by AtoriBirb**
## About The Pull Request

This pr swaps out the old energy gun and advanced energy gun with a slightly modified sprite that is less used in the game, hopefully to people's liking.

OH it also makes the gun a normal size so it can fit in your bag like the HoS gun, since it's a pistol after all.

## Why It's Good For The Game

Cooler guns are always a win in my book.
image

Old Energy:
image
Old Advanced Energy:
image
## Changelog
:cl:
imageadd: added alt pulse laser pistol sprites to use as the energy pistol
balance: energy guns are now classified as pistols and fit into bags
/:cl:

### CODE REVIEW

**Comment by atakiya** [comment]
Added the balance patch to the changelog. Please don't forget that next time ❤️

**Review by atakiya — APPROVED** [review]
Good from my side!

**Comment by Azarak** [comment]
The colored stripes make it harder to discern shot type at a glance.

Regarding gun balance i would much prefer if guns were bulky and held much more ammunition so its harder to stack and conceal them.

**Comment by atakiya** [comment]
> The colored stripes make it harder to discern shot type at a glance.
>
Kind of agree, but we're not aiming for a super fast gameplay style either, so there should be ample of time to check on your gun.
 
> Regarding gun balance i would much prefer if guns were bulky and held much more ammunition so its harder to stack and conceal them, but gun balance can be adressed later.
>
Agree, but guns have to be balanced later on fully anyways.

**Comment by AtoriBirb** [comment]
We can have that discussion at some point and look at the numbers if you'd like

**Review by Azarak — APPROVED** [review]

**Pull request merged**
