### PR TITLE
Repository spring cleaning

### PR DESCRIPTION
**Pull request by atakiya**
## About The Pull Request
Removes a bunch of old files, tools and other junk.

Bumps our minimum version to `514` (`513` for client connections)
This was already enforced in production and CI, but now the repo will reflect that.

.gitignore was also fixed to now include excluded directories properly, so certain GUIs like vscode won't show the `/cfg`, `/data` or `/tmp` directory as tracked in git anymore.

## Changelog
:cl:
server: Minimum BYOND version for compiling and hosting has been raised to 514
/:cl:

### CODE REVIEW

**Comment by CypressBz** [comment]
Has this removed any notable features?

**Review by Azarak — APPROVED** [review]
seems fine to me but you probably know more if anything there is required

**Comment by Azarak** [comment]
> Has this removed any notable features?

It doesn't change any game content or game systems

**Comment by CypressBz** [comment]
> It doesn't change any game content or game systems
Rad.

**Pull request merged**
