### PR TITLE
Old loot

### PR DESCRIPTION
**Pull request by Shanewayne9**
## About The Pull Request
Returning the old space loot ( According to citadel-skyrat code ) to the proper ruins with added feedback from players back into the game accordingly. The changed of the ruins in the changelog

## Why It's Good For The Game
With the added exploration system, it's harder to get to ruins. So assistants won't get the said loot easier and it makes space exploring better and payout more interesting for those who dare to go to them

## Changelog
:cl:
Space Ruins, Abandon zoo, 
Del: Eva suit
Del: Eva helmet
Add: medical hardsuit

Space Ruins, Big Derelict , 
Add: 1 more mag .45

Space Ruins, caravan ambush, - The pistol was not added due to feedback - 
Del: disabler 
Add: shotgun 

Space Ruins, crashed ship, 
Del: Eva suit
Del: Eva helmet
Add: Dark green spacesuit
Add: Dark green space helmet

Space Ruins, deepstorage, 
Del: Eva suit storage
Add: Mining eva suit storage
Add: WT550 gun x2
Add: WT550 ammo x2

Space Ruins, djstation, 
Del: Eva suit
Del: Eva helmet
Add: Orange spacesuit
Add: Orage space helmet

Space Ruins, gasthelizard, 
Del: Eva suit storage
Add: Security hardsuit storage

Space Ruins, oldaisat, 
Fix: Space cash in the wall

Space Ruins, onehalf, - in the safe -
Del: Eva suit
Del: Eva suit helmet
Add: Syndicate blood hardsuit

Space Ruins, originatcontext - paper dungeon -
Add: origami book

Space Ruins, turreted outpost, -other items werent due to feedback-
Add: Riot helmet

Space Ruins, whiteshipruin, 
Del: Eva helmet x2
Del: Eva suit x2
Add: medicial hardsuit x2

shuttle, whiteship_box, 
Del: Eva suit stroage x2
Add: Medicial hardsuits storage x2
:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
In the soon future there will be more shuttles accessible for people all around, so the barrier of entry wont be harder.
I believe the Space Bunker ruin only had 1 WT?
I like the variety of suits and I dont think the guns are too excessive(except the duplicate WT in the bunker), but I dont really feel strong way one or another, so up to @atakiya

**Comment by atakiya** [comment]
> In the soon future there will be more shuttles accessible for people all around, so the barrier of entry wont be harder.
> I believe the Space Bunker ruin only had 1 WT?
> I like the variety of suits and I dont think the guns are too excessive(except the duplicate WT in the bunker), but I dont really feel strong way one or another, so up to @atakiya

Agreed. A bit eh about weapons myself, but for now it is whatever and I like this more than having bleh loot. +1

**Comment by atakiya** [comment]
@Shanewayne9 Do fix your changelog please, it is malformed.

The changelog in THAT part of the PR is **player facing**, this means, add anything players should know or care about.
I.e. for this it could be "`rebalance: Re-adjusted the loot table for space ruins to account for longer travel`" or something similar.

I am also not sure how well the TG script we are using currently handles non-label entries in between the :cl:'s, so please leave them out for now. You could just move that entire section into the normal PR body if you want instead, to leave a changelog for maintainers/contributors looking over this PR.

**Review by atakiya — CHANGES_REQUESTED** [review]
Forgot this exists. See my comment above.

**Comment by atakiya** [comment]
..also are those files in the root?

**Comment by Shanewayne9** [comment]
When I check there was 2 but it can be lowered down to 1 WT also
@atakiya wait its in the root files?

**Comment by atakiya** [comment]
> When I check there was 2 but it can be lowered down to 1 WT also
> @atakiya wait its in the root files?

image

**Comment by Shanewayne9** [comment]
@atakiya oh jeez, sorry about that must have not checked it over where  I place it last night

**Comment by CypressBz** [comment]
Hey I'm going over all the ruins with a beauty/feature/content pass, you cool if I take your list of changes and put them into my upcoming ruin beatification pr?

**Comment by CypressBz** [comment]
I ended up adding many of these changes to #363, I hope that's alright, I hope the new face lift does them justice.

**Pull request closed without merging**
