### PR TITLE
Clothing Port + Minor Loadout fixes

### PR DESCRIPTION
**Pull request by EmilitiaEnnehrt**
## About The Pull Request
Ports and touched upon 6 new articles of clothing from Paradise Station and Citadel RP, including a black trench coat, brown trench coat, gentleman's greatcoat, western coat, ladies victorian coat, and ladies coat.

They are added to the loadout screen and clothingsmate vendors alike
image

Also edited the bomber jacket to be more bomber-like.
image

Fix a small typo in the code where Zebra scarf wasn't correctly referred to.

## Why It's Good For The Game
More clothing choices + aesthetic.

## Changelog
:cl:
add: Ported and added 6 new jackets and coats 
qol: added new clothings to loadout and vendors
fix: corrected loadout pathfinding
fix: touched up on the bomber's jacket to be more puffy and less plain.
imageadd: added 6 new sets of sprites for clothing including item version
spellcheck: corrected a typo in the loadout code
/:cl:

### CODE REVIEW

**Comment by EmilitiaEnnehrt** [comment]
Sincere apologies for the commit mess, tried something but ended up having more headaches trying to clear those commits, even changing branch, regardless this hopefully doesn't happen again.

**Comment by atakiya** [comment]
> Sincere apologies for the commit mess, tried something but ended up having more headaches trying to clear those commits, even changing branch, regardless this hopefully doesn't happen again.

Shouldn't matter too much as we squash commits into one on merge, but if you want to keep it clean regardless, I can advise to learn to use `git rebase -i`

**Comment by Azarak** [comment]
Put the object icons inside `icons/obj/clothing/suits.dmi` and not `icons/horizon/obj/clothing/suits.dmi` We are deprecating our modular files, also I'm fairly sure you've got missing icons that way

**Comment by EmilitiaEnnehrt** [comment]
> Put the object icons inside `icons/obj/clothing/suits.dmi` and not `icons/horizon/obj/clothing/suits.dmi` We are deprecating our modular files, also I'm fairly sure you've got missing icons that way

I think the reason for it was simpler than that, I finished my DMI before updating my fork with the upstream, which I didn't realize that .dmi just sorta replaces, not adds to it, so it was a conflict with this PR. #1022

It should work now.

**Comment by Azarak** [comment]
> > Put the object icons inside `icons/obj/clothing/suits.dmi` and not `icons/horizon/obj/clothing/suits.dmi` We are deprecating our modular files, also I'm fairly sure you've got missing icons that way
> 
> I think the reason for it was simpler than that, I finished my DMI before updating my fork with the upstream, which I didn't realize that .dmi just sorta replaces, not adds to it, so it was a conflict with this PR. #1022
> 
> It should work now.

What I mean is that the object icons shouldn't be inside the /horizon subfolder, that one is meant to be deprecated. The icon files for objects as the clothes lay on the ground wont show up either

**Comment by EmilitiaEnnehrt** [comment]
> > > Put the object icons inside `icons/obj/clothing/suits.dmi` and not `icons/horizon/obj/clothing/suits.dmi` We are deprecating our modular files, also I'm fairly sure you've got missing icons that way
> > 
> > 
> > I think the reason for it was simpler than that, I finished my DMI before updating my fork with the upstream, which I didn't realize that .dmi just sorta replaces, not adds to it, so it was a conflict with this PR. #1022
> > It should work now.
> 
> What I mean is that the object icons shouldn't be inside the /horizon subfolder, that one is meant to be deprecated. The icon files for objects as the clothes lay on the ground wont show up either

oh huh, sorry, didn't realize there's an entire other file, gonna fix that, my bad.

**Review by Azarak — APPROVED** [review]

**Pull request merged**
