### PR TITLE
Pubby Fixes and changes Vol 3

### LINKED ISSUE #661: Mismatching pipes between distro and security LS on Pubby
## About
Map: Pubby Station (revision 505e2f3d9f698b3048c65c886cff84d356a9363f )
Life support distribution piping is broken between the Security department and the rest of the station.
Cause is pipe colour mismatch.

### LINKED ISSUE #704: Missing organbox or organ printer for medical Pubby Map
Missing organbox or organ printer for medical.

_Originally posted by @atakiya in https://github.com/hrzntal/horizon/issues/634#issuecomment-1014253132_

### LINKED ISSUE #705: Stacked Lattices pubby map
- [x] `129, 221, 3`
- [x] `138, 205, 3`
- [x] `146, 86, 3`
- [x] `146, 84, 3`
- [x] `120, 205, 3`
- [x] `129, 222, 3`

_Originally posted by @atakiya in https://github.com/hrzntal/horizon/issues/634#issuecomment-1009472400_

### LINKED ISSUE #708: Pubby: Change change atmos mixing system
### Type of Request

Change

### About the Request

Remove atmos mixing system and replace with layer adapters under each output from the tanks.
Add tank connectors and pump to each tank.

- [x] Remove Yellow Mixing loop
- [x] Add layer adapters under tank outputs
- [x] add pumps and tank connectors
- [x] tidy central area and decorate

### Why should it be considered

The mixing loop used to be an easy way for AI Antags to mess with station air. or for lazy peeps to mix gases. this is not required for our server. and will be replaced with a nicer setup to allow more creative work with out the hassle of ripping up all the piping.

### PR DESCRIPTION
**Pull request by MissFox0810**
## About The Pull Request
Large Map PR to clean up outstanding Issues.

Resolves #708 - Atmos Redesign
Fixes #705 - Stacked Lattices 
Fixes #704 - Missing Limb Grower
Fixes #661 - Security supply pipe color

Largest changes are atmos redesign. Pubby atmos no longer has mixing loop.
This has been replaced with tank connectors and layer adapters for each tank.
Room has been moved around a bit to make look nice.

image

## Changelog
:cl:
fix: Pubby - Stacked Lattices
fix: Pubby - Added missing limb grower to medical
fix: Pubby - Recolored all pipes in secuirty area to match rest of station
qol: Pubby - Atmos room redesign, no more mixing loop, now layer adapters for each tank
/:cl:

### CODE REVIEW

**Comment by MissFox0810** [comment]
Missed a bug

**Comment by atakiya** [comment]
Would it be possible to get a preliminary band-aid patch for the air tank in this?
See screenshot below (excuse the shittyness, made this in 2 minutes with shareX)

but basically, gas valves on Nitrogen and Oxygen sources, move mixer up (as the gas valve on oxygen pushes the pipe a bit up, but that is blocked)
image

**Comment by atakiya** [comment]
Did you also remove the `acted_explosions` on L48862?
image

This variable does not exist in code anymore, causing a runtime on init of the APC.

**Comment by MissFox0810** [comment]
Oh yea. need to clean up the APCs. thanks for reminding me

**Review by atakiya — APPROVED** [review]

**Pull request merged**
